import 'package:flutter/material.dart';
import 'package:newsworlds/components/deatiledscreencomponents.dart';

import '../models/mymodels.dart';

class ChipsDetailScreen extends StatefulWidget {
  int? recievedIndex;
  String? recievedQuery;

  ChipsDetailScreen(this.recievedIndex, this.recievedQuery);

  @override
  _ChipsDetailScreenState createState() => _ChipsDetailScreenState();
}

class _ChipsDetailScreenState extends State<ChipsDetailScreen> {
  Autogenerated? autogenerated;

  @override
  void initState() {
    super.initState();
    detailedScreenComponents
        .getData(widget.recievedQuery)
        .then((value) => autogenerated = value);
    setState(() {});
  }

  DetailedScreenComponents detailedScreenComponents =
      DetailedScreenComponents();

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final TextTheme textTheme = theme.textTheme;
    return SafeArea(
      child: Scaffold(
        backgroundColor: theme.scaffoldBackgroundColor,
        appBar: AppBar(
            backgroundColor: theme.primaryColor,
            title: Text(
              'Details',
              style: textTheme.subtitle1!
                  .copyWith(fontWeight: FontWeight.w700, fontSize: 28.0),
            )),
        body: detailedScreenComponents.buildFutureBuilder(
            widget.recievedIndex, widget.recievedQuery),
      ),
    );
  }
}
