import 'package:flutter/material.dart';
import 'package:newsworlds/components/screencomponents.dart';

import '../models/mymodels.dart';

class Screen2 extends StatefulWidget {
  int? recievedIndex;
  Screen2(this.recievedIndex);

  @override
  _Screen2State createState() => _Screen2State();
}

class _Screen2State extends State<Screen2> {
  Autogenerated? autogenerated;

  @override
  void initState() {
    super.initState();
    screenComponents.getData().then((value) => autogenerated = value);
    setState(() {});
  }

  ScreenComponents screenComponents = ScreenComponents();

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final TextTheme textTheme = theme.textTheme;
    return SafeArea(
      child: Scaffold(
        backgroundColor: theme.scaffoldBackgroundColor,
        appBar: AppBar(
            backgroundColor: theme.primaryColor,
            title: Text(
              'Details',
              style: textTheme.subtitle1!
                  .copyWith(fontWeight: FontWeight.w700, fontSize: 28.0),
            )),
        body: screenComponents.buildFutureBuilder(widget.recievedIndex),
      ),
    );
  }
}
