import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import '../models/mymodels.dart';
import '../screens/screen2.dart';

class Components {
  String urlSite =
      'https://newsapi.org/v2/top-headlines?sources=bbc-news&apiKey=4247934768314a6eb9606ece3e4c8b8d';
  String? sentUrl;

  String? imagelink;
  String? title;
  String? description;
  int? totalnumber;
  int? outputtedIndex;

  Future<Autogenerated> getData() async {
    http.Response data = await http.get(Uri.parse(urlSite));

    print("mycode is ${data.statusCode.toString()}");

    var jsonData = jsonDecode(data.body);
    return Autogenerated.fromJson(jsonData);
  }

  FutureBuilder<Autogenerated> buildFutureBuilder() {
    return FutureBuilder(
      future: getData(),
      builder: (BuildContext context, AsyncSnapshot<Autogenerated> snapshot) {
        final ThemeData theme = Theme.of(context);
        final TextTheme textTheme = theme.textTheme;
        if (snapshot.data == null) {
          return Container(
            height: 800,
            width: 600,
            child: Center(child: CircularProgressIndicator()),
          );
        } else {
          return ListView.builder(
            shrinkWrap: true,
            scrollDirection: Axis.vertical,
            itemCount: snapshot.data!.articles!.length,
            itemBuilder: (BuildContext context, int index) {
              return GestureDetector(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => Screen2(index),
                    ),
                  );
                },
                child: Container(
                    padding: EdgeInsets.all(12.0),
                    margin: EdgeInsets.all(10.0),
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                        color: theme.secondaryHeaderColor),
                    constraints: BoxConstraints(maxHeight: 300.0),
                    child: Stack(
                      children: [
                        Image.network(
                          snapshot.data!.articles![index].urlToImage.toString(),
                          fit: BoxFit.cover,
                          height: 180.0,
                          width: 400.0,
                        ),
                        Column(
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Text(
                              snapshot.data!.articles![index].title.toString(),
                              style: textTheme.headline6!.copyWith(
                                  fontWeight: FontWeight.w700, fontSize: 17.0),
                              overflow: TextOverflow.ellipsis,
                              maxLines: 2,
                            ),
                            Text(
                              snapshot.data!.articles![index].description
                                  .toString(),
                              style: textTheme.headline6!.copyWith(
                                  fontWeight: FontWeight.w300, fontSize: 14.0),
                              overflow: TextOverflow.ellipsis,
                              maxLines: 2,
                            ),
                          ],
                        )
                      ],
                    )),
              );
            },
          );
        }
      },
    );
  }
}
