import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import '../models/mymodels.dart';

class DetailedScreenComponents {
  Source? source;
  String? author;
  String? title;
  String? description;
  String? url;
  String? urlToImage;
  String? publishedAt;
  String? content;

  Future<Autogenerated> getData(recievedQuery) async {
    http.Response data = await http.get(Uri.parse(
        'https://newsapi.org/v2/everything?q=${recievedQuery}&from=2021-10-16&sortBy=popularity&apiKey=4247934768314a6eb9606ece3e4c8b8d'));

    print("mycode is ${data.statusCode.toString()}");

    var jsonData = jsonDecode(data.body);
    return Autogenerated.fromJson(jsonData);
  }

  FutureBuilder<Autogenerated> buildFutureBuilder(
      recievedIndex, recievedQuery) {
    return FutureBuilder(
      future: getData(recievedQuery),
      builder: (BuildContext context, AsyncSnapshot<Autogenerated> snapshot) {
        if (snapshot.data == null) {
          return Container(
            height: 800,
            width: 600,
            child: Center(child: CircularProgressIndicator()),
          );
        } else {
          return ListView.builder(
            scrollDirection: Axis.vertical,
            itemCount: 1,
            itemBuilder: (BuildContext context, int index) {
              final ThemeData theme = Theme.of(context);
              final TextTheme textTheme = theme.textTheme;
              index = recievedIndex!;
              return Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Image.network(
                    snapshot.data!.articles![recievedIndex!].urlToImage
                        .toString(),
                    fit: BoxFit.cover,
                    height: 250.0,
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    snapshot.data!.articles![recievedIndex!].title.toString(),
                    style: textTheme.subtitle1!
                        .copyWith(fontWeight: FontWeight.w700, fontSize: 26.0),
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    'Description : ${snapshot.data!.articles![recievedIndex!].description.toString()}',
                    style: textTheme.headline6!
                        .copyWith(fontSize: 18.0, fontWeight: FontWeight.w300),
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    'Content : ${snapshot.data!.articles![recievedIndex!].content.toString()}',
                    style: textTheme.headline6!
                        .copyWith(fontSize: 18.0, fontWeight: FontWeight.w300),
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    'Published at : ${snapshot.data!.articles![recievedIndex!].publishedAt.toString()}',
                    style: textTheme.headline6!
                        .copyWith(fontSize: 18.0, fontWeight: FontWeight.w300),
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    'Author : ${snapshot.data!.articles![recievedIndex!].author.toString()}',
                    style: textTheme.headline6!
                        .copyWith(fontSize: 18.0, fontWeight: FontWeight.w300),
                  ),
                  SizedBox(
                    height: 20.0,
                  ),
                  Text(
                    'For more information visit : ${snapshot.data!.articles![recievedIndex!].url.toString()}',
                    style: textTheme.headline6!
                        .copyWith(fontSize: 18.0, fontWeight: FontWeight.w300),
                  ),
                ],
              );
            },
          );
        }
      },
    );
  }
}
